### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by marckohlbrugge** [cou929/stability-sdk-ruby#4]
Thanks for your work on this! I was considering creating my own gem, but saw you already did the hard work 👍

The one thing that's currently keeping me from using the gem is the lack of a license. Would you consider licensing this gem? For example under the MIT license.

Thanks!

**Comment by cou929** [comment]
Thank you for your feedback.
I will add a license within a few days. I would like to select the MIT or something similar.

**Comment by cou929** [comment]
I've added the MIT license file in https://github.com/cou929/stability-sdk-ruby/pull/8
